"""
Comprehensive skill extraction using a large dictionary of 200+ tech skills.
Uses regex word-boundary matching to detect skills in resume/JD text.
"""
import re

SKILLS_DB = {
    # ── PROGRAMMING LANGUAGES ──
    "Python": r"\bpython\b",
    "Java": r"\bjava\b(?!\s*script)",
    "JavaScript": r"\bjavascript\b|\bjs\b",
    "TypeScript": r"\btypescript\b|\bts\b",
    "C": r"\bc\b(?!\+|\#|ss)",
    "C++": r"\bc\+\+\b|\bcpp\b",
    "C#": r"\bc#\b|\bcsharp\b|c\s*sharp",
    "Go": r"\bgolang\b|\bgo\b(?:\s+lang)",
    "Rust": r"\brust\b",
    "Ruby": r"\bruby\b",
    "PHP": r"\bphp\b",
    "Swift": r"\bswift\b",
    "Kotlin": r"\bkotlin\b",
    "Scala": r"\bscala\b",
    "R": r"\br\b(?:\s+programming|\s+language|\s+studio)",
    "MATLAB": r"\bmatlab\b",
    "Perl": r"\bperl\b",
    "Dart": r"\bdart\b",
    "Lua": r"\blua\b",
    "Haskell": r"\bhaskell\b",
    "Shell Scripting": r"\bshell\b|\bbash\b|\bshell\s*script",
    "SQL": r"\bsql\b",
    "Solidity": r"\bsolidity\b",

    # ── FRONTEND FRAMEWORKS & LIBRARIES ──
    "React.js": r"\breact\b|\breactjs\b|\breact\.js\b",
    "Angular": r"\bangular\b|\bangularjs\b",
    "Vue.js": r"\bvue\b|\bvuejs\b|\bvue\.js\b",
    "Next.js": r"\bnext\.js\b|\bnextjs\b",
    "Nuxt.js": r"\bnuxt\b",
    "Svelte": r"\bsvelte\b",
    "jQuery": r"\bjquery\b",
    "Bootstrap": r"\bbootstrap\b",
    "Tailwind CSS": r"\btailwind\b",
    "Material UI": r"\bmaterial\s*ui\b|\bmui\b",
    "Chakra UI": r"\bchakra\b",
    "Ant Design": r"\bant\s*design\b|\bantd\b",
    "Sass/SCSS": r"\bsass\b|\bscss\b",
    "Redux": r"\bredux\b",
    "Zustand": r"\bzustand\b",
    "Three.js": r"\bthree\.js\b|\bthreejs\b",
    "D3.js": r"\bd3\b|\bd3\.js\b",
    "Webpack": r"\bwebpack\b",
    "Vite": r"\bvite\b",
    "HTML": r"\bhtml\b",
    "CSS": r"\bcss\b",

    # ── BACKEND FRAMEWORKS ──
    "Node.js": r"\bnode\.js\b|\bnodejs\b|\bnode\b",
    "Express.js": r"\bexpress\b|\bexpressjs\b",
    "Django": r"\bdjango\b",
    "Flask": r"\bflask\b",
    "FastAPI": r"\bfastapi\b",
    "Spring Boot": r"\bspring\s*boot\b|\bspring\b",
    "Ruby on Rails": r"\brails\b|\bruby\s*on\s*rails\b",
    "Laravel": r"\blaravel\b",
    "ASP.NET": r"\basp\.net\b|\basp\s*net\b",
    ".NET": r"\.net\b|\bdotnet\b",
    "Gin": r"\bgin\b(?:\s+framework)?",
    "Fiber": r"\bfiber\b(?:\s+go)?",
    "NestJS": r"\bnestjs\b|\bnest\.js\b",
    "GraphQL": r"\bgraphql\b",
    "gRPC": r"\bgrpc\b",
    "REST API": r"\brest\s*api\b|\brestful\b",
    "WebSocket": r"\bwebsocket\b",

    # ── DATABASES ──
    "MySQL": r"\bmysql\b",
    "PostgreSQL": r"\bpostgresql\b|\bpostgres\b",
    "MongoDB": r"\bmongodb\b|\bmongo\b",
    "SQLite": r"\bsqlite\b",
    "Redis": r"\bredis\b",
    "Cassandra": r"\bcassandra\b",
    "DynamoDB": r"\bdynamodb\b",
    "Firebase": r"\bfirebase\b",
    "Supabase": r"\bsupabase\b",
    "Oracle DB": r"\boracle\b",
    "SQL Server": r"\bsql\s*server\b|\bmssql\b",
    "Elasticsearch": r"\belasticsearch\b|\belastic\b",
    "Neo4j": r"\bneo4j\b",
    "CouchDB": r"\bcouchdb\b",
    "MariaDB": r"\bmariadb\b",
    "InfluxDB": r"\binfluxdb\b",

    # ── CLOUD & DEVOPS ──
    "AWS": r"\baws\b|\bamazon\s*web\s*services\b",
    "Azure": r"\bazure\b",
    "Google Cloud": r"\bgcp\b|\bgoogle\s*cloud\b",
    "Docker": r"\bdocker\b",
    "Kubernetes": r"\bkubernetes\b|\bk8s\b",
    "Terraform": r"\bterraform\b",
    "Ansible": r"\bansible\b",
    "Jenkins": r"\bjenkins\b",
    "GitHub Actions": r"\bgithub\s*actions\b",
    "GitLab CI": r"\bgitlab\s*ci\b",
    "CircleCI": r"\bcircleci\b",
    "Nginx": r"\bnginx\b",
    "Apache": r"\bapache\b",
    "Heroku": r"\bheroku\b",
    "Vercel": r"\bvercel\b",
    "Netlify": r"\bnetlify\b",
    "DigitalOcean": r"\bdigitalocean\b",
    "Linux": r"\blinux\b|\bubuntu\b|\bcentos\b|\bdebian\b",
    "CI/CD": r"\bci/?cd\b|\bcontinuous\s*(integration|delivery|deployment)\b",
    "Prometheus": r"\bprometheus\b",
    "Grafana": r"\bgrafana\b",
    "ELK Stack": r"\belk\b",
    "Serverless": r"\bserverless\b|\blambda\b",
    "Microservices": r"\bmicroservices?\b",
    "Load Balancing": r"\bload\s*balanc",

    # ── DATA SCIENCE & ML ──
    "Machine Learning": r"\bmachine\s*learning\b|\bml\b",
    "Deep Learning": r"\bdeep\s*learning\b|\bdl\b",
    "TensorFlow": r"\btensorflow\b|\btf\b",
    "PyTorch": r"\bpytorch\b",
    "Keras": r"\bkeras\b",
    "Scikit-learn": r"\bscikit[\s\-]*learn\b|\bsklearn\b",
    "Pandas": r"\bpandas\b",
    "NumPy": r"\bnumpy\b",
    "Matplotlib": r"\bmatplotlib\b",
    "Seaborn": r"\bseaborn\b",
    "OpenCV": r"\bopencv\b",
    "NLP": r"\bnlp\b|\bnatural\s*language\s*processing\b",
    "Computer Vision": r"\bcomputer\s*vision\b|\bcv\b",
    "Hugging Face": r"\bhugging\s*face\b|\btransformers\b",
    "LangChain": r"\blangchain\b",
    "LLM": r"\bllm\b|\blarge\s*language\s*model",
    "GPT": r"\bgpt\b",
    "BERT": r"\bbert\b",
    "Generative AI": r"\bgenerative\s*ai\b|\bgen\s*ai\b",
    "Data Visualization": r"\bdata\s*vis",
    "Tableau": r"\btableau\b",
    "Power BI": r"\bpower\s*bi\b",
    "Apache Spark": r"\bspark\b|\bpyspark\b",
    "Hadoop": r"\bhadoop\b",
    "Airflow": r"\bairflow\b",
    "MLflow": r"\bmlflow\b",
    "Kubeflow": r"\bkubeflow\b",
    "Feature Engineering": r"\bfeature\s*engineer",
    "Data Pipeline": r"\bdata\s*pipeline\b|\betl\b",
    "Statistics": r"\bstatistics\b|\bstatistical\b",
    "A/B Testing": r"\ba/?b\s*test",
    "Reinforcement Learning": r"\breinforcement\s*learning\b|\brl\b",
    "GANs": r"\bgans?\b|\bgenerative\s*adversarial\b",
    "Time Series": r"\btime\s*series\b",
    "Recommendation Systems": r"\brecommend",
    "XGBoost": r"\bxgboost\b",
    "Random Forest": r"\brandom\s*forest\b",
    "Neural Networks": r"\bneural\s*network",
    "CNN": r"\bcnn\b|\bconvolutional\b",
    "RNN": r"\brnn\b|\brecurrent\b",
    "LSTM": r"\blstm\b",
    "SVM": r"\bsvm\b|\bsupport\s*vector\b",

    # ── MOBILE DEVELOPMENT ──
    "React Native": r"\breact\s*native\b",
    "Flutter": r"\bflutter\b",
    "Android": r"\bandroid\b",
    "iOS": r"\bios\b",
    "SwiftUI": r"\bswiftui\b",
    "Jetpack Compose": r"\bjetpack\s*compose\b",
    "Xcode": r"\bxcode\b",
    "Android Studio": r"\bandroid\s*studio\b",
    "Expo": r"\bexpo\b",

    # ── TESTING ──
    "Selenium": r"\bselenium\b",
    "Cypress": r"\bcypress\b",
    "Jest": r"\bjest\b",
    "JUnit": r"\bjunit\b",
    "Pytest": r"\bpytest\b",
    "Mocha": r"\bmocha\b",
    "Playwright": r"\bplaywright\b",
    "Postman": r"\bpostman\b",
    "Unit Testing": r"\bunit\s*test",
    "Integration Testing": r"\bintegration\s*test",
    "Test Automation": r"\btest\s*automat|\bautomation\s*test",
    "TDD": r"\btdd\b|\btest[\s\-]*driven",
    "BDD": r"\bbdd\b|\bbehavior[\s\-]*driven",
    "Load Testing": r"\bload\s*test|\bjmeter\b",

    # ── TOOLS & VERSION CONTROL ──
    "Git": r"\bgit\b(?!hub|lab)",
    "GitHub": r"\bgithub\b",
    "GitLab": r"\bgitlab\b",
    "Bitbucket": r"\bbitbucket\b",
    "JIRA": r"\bjira\b",
    "Confluence": r"\bconfluence\b",
    "Slack": r"\bslack\b",
    "Figma": r"\bfigma\b",
    "Adobe XD": r"\badobe\s*xd\b",
    "VS Code": r"\bvs\s*code\b|\bvscode\b",

    # ── SECURITY ──
    "Cybersecurity": r"\bcyber\s*security\b",
    "Ethical Hacking": r"\bethical\s*hack",
    "Penetration Testing": r"\bpenetration\s*test|\bpentest\b",
    "OWASP": r"\bowasp\b",
    "Cryptography": r"\bcryptograph",
    "Network Security": r"\bnetwork\s*security\b",
    "Firewall": r"\bfirewall\b",
    "SIEM": r"\bsiem\b",
    "SOC": r"\bsoc\b",
    "Vulnerability Assessment": r"\bvulnerability\b",

    # ── BLOCKCHAIN ──
    "Blockchain": r"\bblockchain\b",
    "Ethereum": r"\bethereum\b",
    "Smart Contracts": r"\bsmart\s*contract",
    "Web3": r"\bweb3\b|\bweb\s*3\b",
    "NFT": r"\bnft\b",
    "DeFi": r"\bdefi\b",

    # ── MESSAGING & STREAMING ──
    "Kafka": r"\bkafka\b",
    "RabbitMQ": r"\brabbitmq\b",
    "Apache Kafka": r"\bapache\s*kafka\b",
    "Celery": r"\bcelery\b",
    "Socket.io": r"\bsocket\.io\b",

    # ── OTHER / SOFT SKILLS ──
    "Agile": r"\bagile\b",
    "Scrum": r"\bscrum\b",
    "Kanban": r"\bkanban\b",
    "Data Structures": r"\bdata\s*structures?\b|\bdsa\b",
    "Algorithms": r"\balgorithm",
    "OOP": r"\boop\b|\bobject[\s\-]*oriented",
    "Design Patterns": r"\bdesign\s*pattern",
    "System Design": r"\bsystem\s*design\b",
    "API Design": r"\bapi\s*design\b",
    "Problem Solving": r"\bproblem[\s\-]*solv",
    "Communication": r"\bcommunication\b",
    "Teamwork": r"\bteamwork\b|\bteam\s*player\b|\bcollaboration\b",
    "Leadership": r"\bleadership\b|\bteam\s*lead\b",
    "Project Management": r"\bproject\s*management\b",
    "Technical Writing": r"\btechnical\s*writ",
    "Public Speaking": r"\bpublic\s*speak|\bpresentation\b",
}


def extract_skills(text):
    """Extract skills from text using comprehensive regex matching."""
    if not text:
        return []
    found = []
    text_lower = text.lower()
    for skill_name, pattern in SKILLS_DB.items():
        if re.search(pattern, text_lower):
            found.append(skill_name)
    return sorted(set(found))